In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.misc
import glob
import sys
# you shouldn't need to make any more imports

In [2]:
g = scipy.misc.imread("/Users/yjc/columbia_course/deep learning/HW/cifar10-hw1/train/0_frog.png")

/Users/yjc/anaconda/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  if __name__ == '__main__':


In [5]:
new_g = g.flatten()/255.0

In [7]:
new_g.shape

(3072,)

In [8]:
for i in range(1,1):
    print(i)

In [9]:
a = np.array([[1,2],[3,4]])

In [12]:
map(a,lambda x:x**2)

TypeError: 'function' object is not iterable

In [15]:
class x:
    def d(self):
        print("Hello world")
    def f(self):
        self.d()
a = x()
a.f()

Hello world


In [18]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [33]:
b = np.linalg.norm(a,axis=0)
print(b)
c = np.square(b)
print(c)
print(np.sum(c))

[ 3.16227766  4.47213595]
[ 10.  20.]
30.0


In [34]:
c/2

array([  5.,  10.])

In [35]:
a = np.array([[-1,2],[3,-4]])

In [36]:
a>0

array([[False,  True],
       [ True, False]], dtype=bool)

In [38]:
np.where(a > 0, 1, 0)


array([[0, 1],
       [1, 0]])

In [39]:
a[0,1]

2

In [40]:
a

array([[-1,  2],
       [ 3, -4]])

In [41]:
a = np.array([[-1,2],[3,-4],[5,6],[7,8]])

In [48]:
a

array([[-1,  2],
       [ 3, -4],
       [ 5,  6],
       [ 7,  8]])

In [49]:
a[[0,1],range(2)]

array([-1, -4])

In [51]:
b = np.array([[2,4],[-1,3]])

In [52]:
a.dot(b)

array([[-4,  2],
       [10,  0],
       [ 4, 38],
       [ 6, 52]])

In [53]:
a@b

array([[-4,  2],
       [10,  0],
       [ 4, 38],
       [ 6, 52]])

In [56]:
for i in reversed(range(3)):
    print(i)

2
1
0


In [57]:
np.expand_dims(np.sum(a,axis=1),axis=1)

array([[ 1],
       [-1],
       [11],
       [15]])

In [58]:
np.sum(a,axis=1)

array([ 1, -1, 11, 15])

In [61]:
for i in range(0,-1,-1):
    print(i)

0


In [66]:
a = np.array([[1,0,0],[1,0,0]])
b = np.array([[0,1,0],[1,0,0]])
a == b

array([[False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [67]:
np.sum(a==b)

4

In [68]:
db = np.expand_dims(np.sum(a, axis=1), axis=1)

In [70]:
np.sum(a, axis=1)

array([1, 1])

In [8]:
a = np.array([[1,2,3],[4,5,6]])
a[[0,0],[0,1]]

array([1, 2])

In [73]:
a.shape

(2, 3)

In [74]:
np.sum(a, axis=1)

array([ 6, 15])

In [75]:
2/128/256


6.103515625e-05

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [5]:
np.sum(a,axis=1)

array([ 6, 15])

In [11]:
a + np.random.normal(size = (2,1))/100

array([[ 1.00874597,  2.00874597,  3.00874597],
       [ 3.99521887,  4.99521887,  5.99521887]])