In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.misc
import glob
import sys
# you shouldn't need to make any more imports

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[0.1,0.5],[0.3,1.2]])
a / b

array([[ 10.        ,   4.        ],
       [ 10.        ,   3.33333333]])

In [6]:
from math import sqrt
sqrt(0.0)

0.0

In [12]:
np.random.random(2,3)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [17]:
a = np.array([[1,-2],[3,4]])

In [20]:
print(a.all()>0)

True


In [24]:
a = np.array([[1,-2],[3,4]])

In [25]:
a[abs(a-2)<=1] = 0

In [30]:
a = np.array([[1,2,3],[4,5,6]])

In [31]:
np.sum(a,axis=0)

array([5, 7, 9])

In [32]:
a / np.sum(a,axis=0)

array([[ 0.2       ,  0.28571429,  0.33333333],
       [ 0.8       ,  0.71428571,  0.66666667]])

In [33]:
from math import sqrt

In [34]:
sqrt(1e-8)

0.0001

In [39]:
a

array([[-4, -3, -2],
       [-1,  0,  1]])

In [40]:
np.sign(a)

array([[-1, -1, -1],
       [-1,  0,  1]])